RHick/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/', include('sales.urls', namespace='sales')),
    path('', include('users.urls', namespace='users')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import LoginView, LoginAPIView, UserDetailView

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('api/login/', LoginAPIView.as_view(), name='api_login'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/user/', UserDetailView.as_view(), name='user-detail'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    mobile_app = models.BooleanField(default=False, verbose_name='Мобильное приложение')
    id_telegram = models.CharField(max_length=50, null=True, blank=True, verbose_name="Телеграмм ID")

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

    def __str__(self):
        return self.user.username

users/views.py
from django.contrib.auth import login, authenticate
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from .serializers import LoginSerializer, UserSerializer
from rest_framework_simplejwt.tokens import RefreshToken
from django.views import View
from django.shortcuts import render, redirect
from django.contrib import messages


class LoginAPIView(APIView):
    permission_classes = [AllowAny]
    http_method_names = ['post', ]

    def post(self, request, *args, **kwargs):
        serializer = LoginSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.validated_data
            login(request, user)
            refresh = RefreshToken.for_user(user)
            return Response({
                "message": "Успешный вход!",
                "user_id": user.id,
                "refresh": str(refresh),
                "access": str(refresh.access_token),
            })
        return Response(serializer.errors, status=400)

    def options(self, request, *args, **kwargs):
        return Response(status=200)


class UserDetailView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        user = request.user
        serializer = UserSerializer(user)
        return Response(serializer.data)


class LoginView(View):
    def get(self, request):
        return render(request, 'users/login_page.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Вы успешно вошли в систему.')
            return redirect('users:dashboard')
        else:
            messages.error(request, 'Неверное имя пользователя или пароль.')
            return render(request, 'users/login_page.html')

users/templates/users/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>RHiK</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
     <link rel="icon" href="{% static 'users/images/favicon/favicon.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
</head>
<body>
<div class="background">
    <div class="shape"></div>
    <div class="shape"></div>
</div>
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <h3><i class="fas fa-user-circle"></i> RHiK</h3>
    <label for="username"><i class="fas fa-user"></i> Логин</label>
    <input type="text" name="username" placeholder="Введите логин" id="username" required>
    <label for="password"><i class="fas fa-lock"></i> Пароль</label>
    <input type="password" name="password" placeholder="Введите пароль" id="password" required>
    <button type="submit">Войти</button>
    <div class="message-container">
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div class="social">
        <div class="go"><i class="fab fa-google"></i> Google</div>
        <div class="fb"><i class="fab fa-facebook"></i> Facebook</div>
    </div>
</form>
<script src="{% static 'users/js/login.js' %}"></script>
</body>
</html>